### ISSUE TITLE
Pass __DIR__ automatically

### ISSUE THREAD

**Issue by oprypin** [schovi/baked_file_system#9]
> Better and more often usage will be this, where you need to locate files in your repository That repository can be in different locations (imagine more ppl working on same program) Use relative path and pass second argument `__DIR__`
>
> This weird API is because how crystal macros and variable/constants resolving in them works. You cant pass any expression in them

But you can specify `__DIR__` as the default macro argument.
Like so:

```bash
/tmp$ cat a.cr 
```
```crystal
require "b"

test "hi"
```
```bash
/tmp$ cat lib/b.cr
```
```crystal
macro test(a, b = __DIR__)
  puts {{b + "/" + a}}
end
```
```bash
/tmp$ crystal a.cr 
/tmp/hi
```

**Comment by schovi** [comment]
@oprypin Will try, but somehow I was not able to achieve it even after discussion on Crystal irc.

**Comment by schovi** [comment]
@oprypin You are right. It works. But it has impact on other part of library.
This works fine now: `BakedFileSystem.load("./something")`

But it change behavior of absolute paths!
Now when you call `BakedFileSystem.load("/home/name")` it loads `/home/name` because of default `source = ""`.
With this upgrade it will because of `source = __DIR__` do `File.join(__DIR__, "/home/name")` which is `/dir/path/home/name` - invalid

What would make sense is to check if first argument is absolute path and ignore the other one. What do you think?

**Comment by schovi** [comment]
Whoa. There is no method to check if path is absolute or relative in Crystal!

**Comment by schovi** [comment]
@oprypin There is branch with update, can you test it?

**Comment by oprypin** [comment]
Hi. I'm not going to run the code, but I can comment on it.

You don't need to check if the path is absolute, just apply this function, which you seem to already have found.

```crystal
File.expand_path("foo.html", "/home") #=> "/home/foo.html"
File.expand_path("/foo.html", "/home") #=> "/foo.html"
```
